header:
  version: 10

local_conf_header:
  qemu configuration: |
    PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
    PACKAGECONFIG:append:pn-qemu-system-native = " gtk+"
  debug-tweaks: |
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    USER_CLASSES ?= "buildhistory buildstats"
    BUILDHISTORY_COMMIT = "1"
    PACKAGE_CLASSES = "package_ipk"
    PATCHRESOLVE = "noop"
    INHERIT += "rm_work"
    RM_WORK_EXCLUDE = "erlang erlang-native nativesdk-erlang"

  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
  general config: |
    SDKMACHINE = "x86_64"
